jwt:
  secretKey: dafdsvdavads
  accessExpiredAt: 86400
  refreshExpiredAt: 604800

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: soul08261204**
    driver-class-name: com.mysql.cj.jdbc.Driver